- name: install nginx
  yum:
    name: nginx
    state: latest

- name: running and enabled nginx
  service:
    name: nginx
    state: started
    enabled: yes
- firewalld: zone=public service=http state=enabled permanent=true immediate=yes
- firewalld: zone=public service=https state=enabled permanent=true immediate=yes
